[theme]
base = "light"
primaryColor = "#245B85"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#202D3A"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false
